### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by FieldsYeh** [nico-bohlinger/RL-X#1]
python experiment.py --config.algorithm.name="ppo.flax" --config.algorithm.total_timesteps=10000 --config.runner.save_model=true
[09-07 20:32:14] [ppo.py:57] INFO - Using device: gpu
[09-07 20:32:20] [ppo.py:368] INFO - Step: 2048
[09-07 20:32:23] [ppo.py:368] INFO - Step: 4096
[09-07 20:32:26] [ppo.py:368] INFO - Step: 6144
[09-07 20:32:28] [ppo.py:368] INFO - Step: 8192
[09-07 20:32:31] [ppo.py:368] INFO - Step: 10240

python experiment.py --config.algorithm.name="ppo.flax" --config.algorithm.total_timesteps=10000 --config.runner.load_model="runs/placeholder/placeholder/1694089610/models/model_best_config_0"
[09-07 20:33:23] [ppo.py:57] INFO - Using device: gpu
[09-07 20:33:25] [runner.py:68] ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/kl/RL-X/experiments/experiment.py", line 6, in <module>
    runner.run()
  File "/home/kl/RL-X/rl_x/runner/runner.py", line 111, in run
    app.run(main_func)
  File "/home/kl/anaconda3/envs/dl39/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/kl/anaconda3/envs/dl39/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/kl/RL-X/rl_x/runner/runner.py", line 150, in _train
    model = self._model_class.load(self._config, env, run_path, writer)
  File "/home/kl/RL-X/rl_x/algorithms/ppo/flax/ppo.py", line 410, in load
    restored_train_state = checkpoints.restore_checkpoint(
  File "/home/kl/anaconda3/envs/dl39/lib/python3.9/site-packages/flax/training/checkpoints.py", line 1121, in restore_checkpoint
    state_dict = serialization.msgpack_restore(checkpoint_contents)
  File "/home/kl/anaconda3/envs/dl39/lib/python3.9/site-packages/flax/serialization.py", line 425, in msgpack_restore
    state_dict = msgpack.unpackb(
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.

**Comment by FieldsYeh** [comment]
add below line will be OK.
jax_file_name = "model_best_jax_"
