### ISSUE TITLE
Does custom_environments.prototype work with ppo.flax?

### ISSUE THREAD

**Issue by FieldsYeh** [nico-bohlinger/RL-X#2]
I've fulfilled the prototype code and make the Connect can working, but encounter problem when run below command. 
python experiment.py --config.algorithm.name="ppo.flax" --config.algorithm.total_timesteps=10000 --config.runner.save_model=true --config.environment.name="custom_environments.prototype"

**Comment by nico-bohlinger** [comment]
What kind of problem do you encounter? Could you provide the exact error message?

**Comment by FieldsYeh** [comment]
[runner.py:68] ERROR - Uncaught exception
Traceback (most recent call last):
  File "/home/rl/RL-X/experiments/experiment.py", line 6, in <module>
    runner.run()
  File "/home/rl/RL-X/rl_x/runner/runner.py", line 111, in run
    app.run(main_func)
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/rl/RL-X/rl_x/runner/runner.py", line 155, in _train
    model.train()
  File "/home/rl/RL-X/rl_x/algorithms/ppo/flax/ppo.py", line 270, in train
    processed_action, storage, self.key = get_action_and_value(self.policy_state, self.critic_state, state, storage, step, self.key)
  File "/home/rl/RL-X/rl_x/algorithms/ppo/flax/ppo.py", line 117, in get_action_and_value
    actions=storage.actions.at[step].set(action),
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 485, in wrapped
    return f(*args, **kwargs)
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 532, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 76, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 109, in _scatter_impl
    y = jnp.broadcast_to(y, tuple(indexer.slice_shape))
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1144, in broadcast_to
    return util._broadcast_to(array, shape)
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 398, in _broadcast_to
    for arr_d, shape_d in safe_zip(arr_shape, shape_tail))
  File "/home/rl/anaconda3/envs/dl39/lib/python3.9/site-packages/jax/_src/util.py", line 71, in safe_zip
    assert len(arg) == n, f'length mismatch: {list(map(len, args))}'
AssertionError: length mismatch: [3, 1]

**Comment by FieldsYeh** [comment]
the difference is that I used 2d Box observation_space instead 1d  Box observation_space.

**Comment by FieldsYeh** [comment]
flatten the 2d Box observation_space to 1d will be OK. Does the algorithm support 2D Box observation space?
